spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password: test
    profiles:
        active: real
    jpa:
        hibernate:
            ddl-auto: update
    properties:
        hibernate:
            default_batch_fetch_size: 100

        mvc:
            pathmatch:
                matching-strategy: ant_path_matcher
#        show_sql: true
#        format_sql: true#spring:
